#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  3 10:30:58 2018

@author: oussama
"""


""" Display image in opencv"""
import cv2


# Display image in separate window
img = cv2.imread('test_dog.jpg')
while True:
    cv2.imshow('dog', img)
    # we wait 1ms and we pressed esc key
    if cv2.waitKey(1) & 0xFF == 27:
        break

cv2.destroyAllWindows()


